language: bash

services:
  - docker

env:
  global:
    - PYTHON37=3.7.5
    - PYTHON36=3.6.9
    - PYTHON35=3.5.7
    - PYTHON27=2.7.17
  matrix:
    - PYTHON_VER="${PYTHON37}" TAGS=3.7,3,latest
    - PYTHON_VER="${PYTHON36}" TAGS=3.6
    - PYTHON_VER="${PYTHON35}" TAGS=3.5
    - PYTHON_VER="${PYTHON27}" TAGS=2.7,2
    - PYTHON_VER="${PYTHON37}" PYTHON_DEV=1 TAGS=3.7-dev,3-dev
    - PYTHON_VER="${PYTHON36}" PYTHON_DEV=1 TAGS=3.6-dev
    - PYTHON_VER="${PYTHON35}" PYTHON_DEV=1 TAGS=3.5-dev
    - PYTHON_VER="${PYTHON27}" PYTHON_DEV=1 TAGS=2.7-dev,2-dev
    - PYTHON_VER="${PYTHON37}" PYTHON_DEV=1 WODBY_USER_ID=501 WODBY_GROUP_ID=20 TAGS=3.7-dev-macos,3-dev-macos
    - PYTHON_VER="${PYTHON36}" PYTHON_DEV=1 WODBY_USER_ID=501 WODBY_GROUP_ID=20 TAGS=3.6-dev-macos
    - PYTHON_VER="${PYTHON35}" PYTHON_DEV=1 WODBY_USER_ID=501 WODBY_GROUP_ID=20 TAGS=3.5-dev-macos
    - PYTHON_VER="${PYTHON27}" PYTHON_DEV=1 WODBY_USER_ID=501 WODBY_GROUP_ID=20 TAGS=2.7-dev-macos,2-dev-macos

script:
  - set -e
  - travis_retry make
  - make test

after_success:
  - . "${TRAVIS_BUILD_DIR}/release.sh"

notifications:
  email:
    recipients:
    - travisci@wodby.com
    on_success: never
    on_failure: always
