name: Build
description: Build python image
inputs:
  version:
    description: version
    required: true
  dev:
    description: dev version of image
    required: false
  user_id:
    description: user id
    required: false
  group_id:
    description: group id
    required: false
  tags:
    description: image tags
    required: true
  username:
    description: docker username
    required: true
  password:
    description: docker password
    required: true
runs:
  using: "composite"
  steps:
  - name: Build image
    env:
      PYTHON_VER: ${{ inputs.version }}
      PYTHON_DEV: ${{ inputs.dev }}
      WODBY_USER_ID: ${{ inputs.user_id }}
      WODBY_GROUP_ID: ${{ inputs.group_id }}
      DOCKER_USERNAME: ${{ inputs.username }}
      DOCKER_PASSWORD: ${{ inputs.password }}
      TAGS: ${{ inputs.tags }}
    run: |
      set -e
      make
      make test
      . $GITHUB_ACTION_PATH/release.sh
    shell: bash
